### ISSUE TITLE
Add slides to the website

### ISSUE THREAD

**Issue by jackiekazil** [18F/hackathons#11]
@nickbristow @adelevie --- do we have the slides stored some where or are they in master deck?

**Comment by nickbristow** [comment]
They are all on the master deck. We can export to ppt

On Tuesday, March 31, 2015, Jackie Kazil notifications@github.com wrote:

> @nickbristow https://github.com/nickbristow @adelevie
> https://github.com/adelevie --- do we have the slides stored some where
> or are they in master deck?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/hackathons/issues/11.

## 

Nick Bristow
18f http://18f.gsa.gov Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by jackiekazil** [comment]
All slides that I have are on the schedule page: http://18f.github.io/hackathons/a11yhack/schedule/
