### ISSUE TITLE
a11yhack - add videos to schedule

### ISSUE THREAD

**Issue by jackiekazil** [18F/hackathons#8]
a11yhack - add videos to schedule & send to DGU also

**Comment by jackiekazil** [comment]
- Christian Vogler: https://www.youtube.com/watch?v=08tyYAhPuVU
- Sue Swenson: (not public yet -- working on it) https://drive.google.com/a/gsa.gov/file/d/0B0C6PKlzps2JelhCUHhWWHBvV0k/view
- Vint Cert: (not public yet -- working on it)
  https://drive.google.com/a/gsa.gov/file/d/0B0C6PKlzps2JbkNXVU5rRXlPLU0/view

^^ possible videos for post -- /cc @kategarklavs

**Comment by jackiekazil** [comment]
Holding off on adding the other videos to the schedule until we have public links. When we have public links, then we will add here: http://18f.github.io/hackathons/a11yhack/schedule/

**Comment by OriHoffer** [comment]
Sue Swenson: http://youtu.be/it5dROtXtXQ
Vint Cerf: http://youtu.be/vko6-DGznyA

Both are set to Private, I will switch them to Public after they run during the event.

**Comment by jackiekazil** [comment]
Done... Sue's video is linked on the site. Waiting to push update for Vint's after it is published.
